import Image from 'next/image'
import React from 'react'
function About() {
  return (
    <>
      <main className=' container mx-auto px-4 py-5'>
        <div className="">
          <div className="div">
            <h3 className='font-[700] text-[#21293c] text-[19px]'>OUR STORY</h3>
          </div>
          <div className="cont1  text-[#7b858a] ">
            <p className=' text-[#000000]  pb-[1.25rem]'> <strong> WELCOME TO PRINTWISH!</strong></p>
            <p className='leading-[27px]  font-[400] pb-[1.25rem] tracking-[.2px]'>PrintWish is a custom printed apparel provider, which uses methods like screen printing, DTG, etc. for printing a wide range of clothing. These clothing include – t-shirts, vests, hoodies, sweatshirts and much more. We help individuals, schools, businesses, sports teams, charities etc. in linking their brand with their customers. With our latest technology, we, at PrintWish print your designs on our high-quality clothing range. Moreover, e also allow the customers to see the preview of how their garment will look with the artwork, design or image. After the customer is satisfied with the preview he/she can go ahead and place the order.</p>
            <p className='pb-[1.25rem] leading-[27px]  font-[400]'>Our Mission – Our mission is to help businesses and individuals in designing, printing and marketing their ideas so that they can express themselves in the best suitable way</p>
            <p className='pb-[1.25rem] leading-[27px] font-[400]'>Our Vision – Our vision is to form a customized apparel design and sales company whose brand will be accepted in the whole world.</p>
          </div>
        </div>

        <div className="cont2 lg:pl-10">
          <div className="font-[400] text-[#7b858a]">
            <p className='pb-[1.25rem] tracking-[.2px]'>Print wish is a leading custom apparel provider and it is always here to inspire you with great customized things like T-shirts, tote bags, hoodies, sweatshirts, Hi-vis, apron, and many more. The customized t-shirt trend is very popular among both teenagers in school and celebrities these shirts having a solid grip on the young fashion world. So if you are looking for a classy, customized T-shirt which can enhance your personality then you are in the right place because print wish customizes T-shirts as you like.<b>Printwish t-shirt printing</b> is better than others and you can also choose every element for your custom t-shirts like the color, the words, the images that will be printed on the shirts, and many more. The <b>Printwish UK</b>  is popular because it provides a greater quality of every customized product to his clients and it also gives a preview of the product and after that, you can place an order. Giving the perfect custom gift for your loved ones can be a tough task so, don’t worry about it because now you can order customized shirts, hoodies, sweatshirts, and much more for your loved ones and it will surely increase your love. To make your events special you can customize your shirts according to events like a birthday party your photograph on the shirt will surely give you great happiness. <b>Printwish t-shirt printing</b> quality is superb amongst all the printing companies, which makes it popular in the world. Print wish company workers have done his work with the full attention which you deserve.</p>
            <p className='pb-[1.25rem] text-black'><strong> Elegant and modish Printwish t-shirt printing </strong> </p>
            <p className='tracking-[.2px] pb-[1.25rem]'>Anyone who is the lover of customized thing, firstly that person checks the quality of printing and designs then place an order to make his money worth it. Print wish is to provide great quality of printing and best services to his clients and they also use traditional and modern methods of printing like screen printing and DTG printing. Print wish also print logo in unique designs on bags, t-shirts, and the other items and that will help in increasing your business market value. Printwish UK is offering a wide range of personalized products at affordable rates, so make your t-shirt or other personalized product to spread your unique messages. Our company has great stuff of t-shirts, hoodies and other items which can use for a long time. Everyone has a dream to wear clothes that his name or favorite character printed on them, so now print wish can make your dream come true. Customized things are ideal and memorable for everyone so to make a good memory with your favorite people customized products are necessary. A rough printing can spoil your whole business value so to make value in the world, best printing is necessary because it leaves a good impact on people so for best printing you have to select print wish.</p>
            <p className='pb-[1.25rem] text-black'><strong>  Printwish UK offers great alluring services  </strong> </p>
            <p className='pb-[1.25rem] tracking-[.2px]'>Printwish UK enables to fulfill the commitment of his valued customers and it is always done his work on time. Printwish t-shirt printing quality is amazing that you can easily afford, for wearing it and flaunt you and it doesn’t have to cross the limit of your bank. Print Wish Company provides tremendous printing designs that can easily highlight your business all over the world. The styles of print wish products distinguish it from other companies. Printwish UK will never disappoint you in any matter whether it is printing of images and text and if you are worried about your look then keep your look fresh with the latest custom Printwish t-shirt printing. Print Wish Company brings you a wide range of trendy custom apparel and you can design your product from a wide range of classy and modern designs. Printwish UK offers an effective and inexpensive way to communicate. Printwish t-shirt printing has fashionable ways to make you beautiful so, don’t hesitate to come and find your favorite style from our company. Our apparels are very comfy and easy to wear and the vibrant color of our product will surely make your environment pleasing for your eyes</p>
          </div>
        </div>

        <div className="cont3 text-[#7b858a] ">
          <div className="div">
            <p className='pb-[1.25rem] text-black'><strong>Printwish UK offers great alluring services</strong></p>
            <p className='pb-[1.25rem] tracking-[.2px]'>Printwish UK offers powerful customer personalized services because we care about our customer and their needs. Print wish have a lot of choices so you just have to share your idea with us we will prove it uniquely. Print wish respects your art but the clean environment around you is necessary for your focus so, we have those items too that can help you while you are cooking or painting. Our great customer services help your business stand out so don’t miss the chance to grow your business in the market. Our customer wish is our main priority so, we work according to your wish and our services are cheap and you can easily afford them. We provide amazing customer service because we aim to provide satisfactory services to individuals worldwide. You want customization and we are giving it so, come and select your favorite cloth. Print wish have a wide range of clothing like sweatshirts, t-shirts, polo, and much more so, order it now to make your personality classy. Printwish t-shirt printing is fine and we design it according to your attitude and personality and it will surely not disturb your budget. Print Wish Company also makes custom tote bags which is a great way to carry items so create your own fun design. So it’s time to get your luxury custom product from print wish for your team, party, or event. Print wish is always focused on one thing and that is how we work is as important as what we work on which makes it more popular.</p>
            <p className='pb-[1.25rem] text-black'><strong>Luxurious products of print wish can change your life in just one click</strong></p>
            <p className='pb-[1.25rem] tracking-[.2px]'>Do you want an eye-catching look? Then, why are you wasting your time? So grab your favorite customized t-shirt, bag, polo, vest, or hoodies as soon as possible from Print wish. The stuff of the products is great and Printwish UK is a well-known company due to his great services. You can make a day special of your friend or your loved ones by giving them customized t-shirts, vests, hi vis, sweatshirts, or hoodies because we print your favorite text, name, image, or photograph on them. Print wish customize products in a digital method which makes them more attractive and can easily catch the eye of people at one glance. Printwish t-shirt printing is magical that makes them more elegant and print wish is working for you to help in grow your business like if you have a business of catering then you can order customize apron for your servants. Print wish also has many color options so you can select your favorite color to make your product more fashionable and unique. We have a wide range of colors for apron and Printwish UK design t-shirts, hoodies, vests, sweatshirts, and other items differently from others. Printwish t-shirt printing is reliable and affordable and we do not compromise on the quality of the product. Print wish custom apparels also develop special emotional connections when you share it with your dearest one.</p>
            <p className='text-black pb-[1.25rem]'><strong>For Classy and stunning looks print wish is always on top</strong></p>
            <p className='tracking-[.2px] pb-[1.25rem]'>Staying on top of the latest fashion trend is tough so print wish is the company that proves you can do it because it designs your outfit as you want. Are you wondering about how to look classy? Then you have to buy custom apparel from print wish at cheap rates. Printwish UK also respect the desires of kids because some kids are the cartoons lover and they want that character on his clothes and print wish do it uniquely to makes the customer happy. Printwish t-shirt printing is incredibly amazing and an awesome shirt can make a huge statement. Print wish design to offer a healthy way for people to express their feelings. If you are craving personalization then you must have to check out our print wish services even at least once you will surely fall in love with our print wish printing. Printwish t-shirt printing design will always be different and better than the last so, show off your trendy side with the print wish t-shirt. Print wish always uses soft and durable stuff in apparel which can be used for a long time. The main goal of print wish is to deliver things exactly as you want to see your product at reasonable rates. Our apparels are very comfy and easy to wear and the vibrant color of our product will surely make your environment pleasing for your eyes.</p>
          </div>
        </div>

        <div className="foeter pt-5">
          <Image className='w-[65%] m-auto' width={400} height={150} src="/images/review.png" alt="" />
        </div>

      </main>


    </>
  )
}
export default About